version: '3.8'

services:
  order-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true

