version: '3.8'

services:
  order-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - order-net

  orderDB:
    image: mysql:latest
    ports:
      - "3305:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - order-net

networks:
  order-net:
    driver: bridge

volumes:
  db-data:
